# Generated by Django 4.1.4 on 2022-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_auto_20221213_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
